Adding simple example of job webhook enhancer
databricks/databricks-sdk-go pull request #371
Opened 2023-04-20 13:14 UTC by flaviomalavazi

Changes:
- Adding handler.go to enhance job webhooks functionality for Databricks workspaces

Use case description:
If one wants to have a more contextualized view of their webhook events in Databricks, they have to use the job runs API in order to gather more details than just the events (`jobs.on_start`, `jobs.on_failure`, `jobs.on_success`). This example handles the webhook event, parses its content to extract the run id and uses it to get the full details of the run and reroute it to another destination (such as slack, internal monitoring tools, etc)

## Changes

## Tests

- [ ] `make test` passing
- [ ] `make fmt` applied
- [ ] relevant integration tests applied

2023-04-20 14:21 UTC, nfx requested changes
this example is not self-contained. i suspect it's an azure function. 

if you want this example to be added - add a README.md, a terraform file to set it all up.

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +	JobWebhook := webhookParser(r)
```suggestion
	jobWebhook := webhookParser(r)
```

variable names have to start with lowercase

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +	Run         struct {
make sure to run `go fmt` on this file

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +	switch EventType := JobWebhook.EventType; EventType {
```suggestion
	switch JobWebhook.EventType {
```

you're not using `EventType` ;)

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +		log.Printf("workspace_id: %v | job_name: %s | job_id: %v | run_id: %v | event: %s | current_action: None", JobWebhook.WorkspaceID, JobWebhook.Job.JobName, JobWebhook.Job.JobID, JobWebhook.Run.RunID
line is too long and unreadable, split it

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +func SendDetailedWebhook(jobMetadata jobs.Run) {
```suggestion
func sendDetailedWebhook(jobMetadata jobs.Run) {
```

un-export this function. there's no need to make this function public if we have just the `main` package.

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +	}))
```suggestion
	w := databricks.Must(databricks.NewWorkspaceClient())
```

it'll already pull from these environment variables, why do you need to specify them explicitly?

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +		panic(err)
```suggestion
		return nil, err
```

why panic?

2023-04-20 14:21 UTC, nfx commented on examples/job-webhook-enhancer/handler.go
> +	JobWebhook := webhookParser(r)
also, just use `json.Unmarshall()` here directly

2023-05-05 09:19 UTC, nfx commented
Following up - is this issue still relevant?

2023-05-06 12:07 UTC, flaviomalavazi commented
> 

Yes, but I'll close this PR, adjust the code and reopen it once the fixes are done!

2023-05-06 12:07 UTC, closed without merging